services:
  bot:
    image: ${REGISTRY}/bot:latest
    build:
      dockerfile: Dockerfile
      cache_from:
        - type=local,src=/tmp/.buildx-cache
      cache_to:
        - type=local,dest=/tmp/.buildx-cache,mode=max
    profiles:
      - build
